name: Bug Report
description: Report a bug or unexpected behavior in the application
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and detailed description of the bug
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected outcome
    validations:
      required: true
      
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually occurred, include error messages if any
    validations:
      required: true
      
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (application is unusable)
        - High (major feature broken)
        - Medium (feature partially broken)
        - Low (minor issue or cosmetic)
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application is affected?
      options:
        - Frontend (UI)
        - Backend (API)
        - Database
        - Authentication
        - Infrastructure
        - Documentation
        - Other
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment
      placeholder: |
        - OS: [e.g., Windows 11, macOS 14, Ubuntu 22.04]
        - Browser: [e.g., Chrome 120, Firefox 121, Safari 17]
        - Application Version: [e.g., v1.0.0, commit SHA]
        - Database: [e.g., Azure SQL, PostgreSQL 15]
    validations:
      required: false
      
  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Include any relevant error logs, stack traces, or console output
      placeholder: Paste error logs here
      render: shell
    validations:
      required: false
      
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain the problem (if applicable)
      placeholder: Drag and drop or paste screenshots here
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, workarounds, or related issues
      placeholder: Links to related issues, possible causes, temporary workarounds, etc.
    validations:
      required: false
