name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
        
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and detailed description of the bug
      placeholder: |
        Describe what happened and what you expected to happen.
        
        You can use task lists to track fixes:
        - [ ] Subtask 1
        - [ ] Subtask 2
        - [ ] Subtask 3
    validations:
      required: true
