name: Roadmap Feature
description: Create an issue for a post-MVP roadmap feature
title: "[ROADMAP] "
labels: ["roadmap", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this roadmap feature request!
        
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and detailed description of the feature
      placeholder: Describe what this feature does and the value it provides
    validations:
      required: true
      
  - type: textarea
    id: business-value
    attributes:
      label: Business Value
      description: Explain the business value and user impact of this feature
      placeholder: How does this improve the user experience or business operations?
    validations:
      required: true
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the requirements that must be met for this feature to be considered complete
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true
      
  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Any technical implementation details or considerations
      placeholder: APIs, integrations, database changes, etc.
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Priority level for this roadmap feature
      options:
        - High
        - Medium
        - Low
    validations:
      required: true
      
  - type: dropdown
    id: phase
    attributes:
      label: Implementation Phase
      description: When should this feature be implemented?
      options:
        - Phase 2 (3-6 months)
        - Phase 3 (6-12 months)
        - Future
    validations:
      required: false
      
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references
      placeholder: Links to documentation, similar implementations, etc.
    validations:
      required: false
